ServerName localhost

<VirtualHost *:80>
    # proceso aparte que corre Python con el venv; /app en el path para importar app.py
    WSGIDaemonProcess libros python-home=/opt/venv python-path=/app
    WSGIProcessGroup libros
    # toda request a / la atiende app.wsgi
    WSGIScriptAlias / /app/app.wsgi
    <Directory /app>
    # permitimos todo acceso
        Require all granted
    </Directory>
</VirtualHost>
